// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/mux.proto

package mux

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SendRequest struct {
	Datum                *Datum   `protobuf:"bytes,1,opt,name=datum,proto3" json:"datum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendRequest) Reset()         { *m = SendRequest{} }
func (m *SendRequest) String() string { return proto.CompactTextString(m) }
func (*SendRequest) ProtoMessage()    {}
func (*SendRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4935fe522b0ff4e1, []int{0}
}

func (m *SendRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendRequest.Unmarshal(m, b)
}
func (m *SendRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendRequest.Marshal(b, m, deterministic)
}
func (m *SendRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendRequest.Merge(m, src)
}
func (m *SendRequest) XXX_Size() int {
	return xxx_messageInfo_SendRequest.Size(m)
}
func (m *SendRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendRequest proto.InternalMessageInfo

func (m *SendRequest) GetDatum() *Datum {
	if m != nil {
		return m.Datum
	}
	return nil
}

type SendResponse struct {
	Received             bool     `protobuf:"varint,1,opt,name=received,proto3" json:"received,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendResponse) Reset()         { *m = SendResponse{} }
func (m *SendResponse) String() string { return proto.CompactTextString(m) }
func (*SendResponse) ProtoMessage()    {}
func (*SendResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4935fe522b0ff4e1, []int{1}
}

func (m *SendResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendResponse.Unmarshal(m, b)
}
func (m *SendResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendResponse.Marshal(b, m, deterministic)
}
func (m *SendResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendResponse.Merge(m, src)
}
func (m *SendResponse) XXX_Size() int {
	return xxx_messageInfo_SendResponse.Size(m)
}
func (m *SendResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendResponse proto.InternalMessageInfo

func (m *SendResponse) GetReceived() bool {
	if m != nil {
		return m.Received
	}
	return false
}

type ListenRequest struct {
	// Filter in data by tag
	IncludeTags []string `protobuf:"bytes,1,rep,name=include_tags,json=includeTags,proto3" json:"include_tags,omitempty"`
	// Filter out data by tag
	ExcludeTags          []string `protobuf:"bytes,2,rep,name=exclude_tags,json=excludeTags,proto3" json:"exclude_tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListenRequest) Reset()         { *m = ListenRequest{} }
func (m *ListenRequest) String() string { return proto.CompactTextString(m) }
func (*ListenRequest) ProtoMessage()    {}
func (*ListenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4935fe522b0ff4e1, []int{2}
}

func (m *ListenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListenRequest.Unmarshal(m, b)
}
func (m *ListenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListenRequest.Marshal(b, m, deterministic)
}
func (m *ListenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListenRequest.Merge(m, src)
}
func (m *ListenRequest) XXX_Size() int {
	return xxx_messageInfo_ListenRequest.Size(m)
}
func (m *ListenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListenRequest proto.InternalMessageInfo

func (m *ListenRequest) GetIncludeTags() []string {
	if m != nil {
		return m.IncludeTags
	}
	return nil
}

func (m *ListenRequest) GetExcludeTags() []string {
	if m != nil {
		return m.ExcludeTags
	}
	return nil
}

type ListenResponse struct {
	Datum                *Datum   `protobuf:"bytes,1,opt,name=datum,proto3" json:"datum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListenResponse) Reset()         { *m = ListenResponse{} }
func (m *ListenResponse) String() string { return proto.CompactTextString(m) }
func (*ListenResponse) ProtoMessage()    {}
func (*ListenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4935fe522b0ff4e1, []int{3}
}

func (m *ListenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListenResponse.Unmarshal(m, b)
}
func (m *ListenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListenResponse.Marshal(b, m, deterministic)
}
func (m *ListenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListenResponse.Merge(m, src)
}
func (m *ListenResponse) XXX_Size() int {
	return xxx_messageInfo_ListenResponse.Size(m)
}
func (m *ListenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListenResponse proto.InternalMessageInfo

func (m *ListenResponse) GetDatum() *Datum {
	if m != nil {
		return m.Datum
	}
	return nil
}

type PingRequest struct {
	Ping                 bool     `protobuf:"varint,1,opt,name=ping,proto3" json:"ping,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingRequest) Reset()         { *m = PingRequest{} }
func (m *PingRequest) String() string { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()    {}
func (*PingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4935fe522b0ff4e1, []int{4}
}

func (m *PingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingRequest.Unmarshal(m, b)
}
func (m *PingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingRequest.Marshal(b, m, deterministic)
}
func (m *PingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingRequest.Merge(m, src)
}
func (m *PingRequest) XXX_Size() int {
	return xxx_messageInfo_PingRequest.Size(m)
}
func (m *PingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PingRequest proto.InternalMessageInfo

func (m *PingRequest) GetPing() bool {
	if m != nil {
		return m.Ping
	}
	return false
}

type PingResponse struct {
	Pong                 bool     `protobuf:"varint,1,opt,name=pong,proto3" json:"pong,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingResponse) Reset()         { *m = PingResponse{} }
func (m *PingResponse) String() string { return proto.CompactTextString(m) }
func (*PingResponse) ProtoMessage()    {}
func (*PingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4935fe522b0ff4e1, []int{5}
}

func (m *PingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingResponse.Unmarshal(m, b)
}
func (m *PingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingResponse.Marshal(b, m, deterministic)
}
func (m *PingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingResponse.Merge(m, src)
}
func (m *PingResponse) XXX_Size() int {
	return xxx_messageInfo_PingResponse.Size(m)
}
func (m *PingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PingResponse proto.InternalMessageInfo

func (m *PingResponse) GetPong() bool {
	if m != nil {
		return m.Pong
	}
	return false
}

// Core datum/event structure
type Datum struct {
	// timestamp of the event (if available)
	UtsEvent *timestamp.Timestamp `protobuf:"bytes,1,opt,name=uts_event,json=utsEvent,proto3" json:"uts_event,omitempty"`
	// timestamp at time of collection
	UtsCollected *timestamp.Timestamp `protobuf:"bytes,2,opt,name=uts_collected,json=utsCollected,proto3" json:"uts_collected,omitempty"`
	// source of the data / event
	// TODO(cmc): should this be an enum?
	//    source --> collector, parser
	Source string `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	// data
	Data string `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	// internal tags for the data
	Tags                 []string `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Datum) Reset()         { *m = Datum{} }
func (m *Datum) String() string { return proto.CompactTextString(m) }
func (*Datum) ProtoMessage()    {}
func (*Datum) Descriptor() ([]byte, []int) {
	return fileDescriptor_4935fe522b0ff4e1, []int{6}
}

func (m *Datum) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Datum.Unmarshal(m, b)
}
func (m *Datum) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Datum.Marshal(b, m, deterministic)
}
func (m *Datum) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Datum.Merge(m, src)
}
func (m *Datum) XXX_Size() int {
	return xxx_messageInfo_Datum.Size(m)
}
func (m *Datum) XXX_DiscardUnknown() {
	xxx_messageInfo_Datum.DiscardUnknown(m)
}

var xxx_messageInfo_Datum proto.InternalMessageInfo

func (m *Datum) GetUtsEvent() *timestamp.Timestamp {
	if m != nil {
		return m.UtsEvent
	}
	return nil
}

func (m *Datum) GetUtsCollected() *timestamp.Timestamp {
	if m != nil {
		return m.UtsCollected
	}
	return nil
}

func (m *Datum) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *Datum) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *Datum) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func init() {
	proto.RegisterType((*SendRequest)(nil), "SendRequest")
	proto.RegisterType((*SendResponse)(nil), "SendResponse")
	proto.RegisterType((*ListenRequest)(nil), "ListenRequest")
	proto.RegisterType((*ListenResponse)(nil), "ListenResponse")
	proto.RegisterType((*PingRequest)(nil), "PingRequest")
	proto.RegisterType((*PingResponse)(nil), "PingResponse")
	proto.RegisterType((*Datum)(nil), "Datum")
}

func init() { proto.RegisterFile("proto/mux.proto", fileDescriptor_4935fe522b0ff4e1) }

var fileDescriptor_4935fe522b0ff4e1 = []byte{
	// 372 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0x41, 0x6b, 0xab, 0x40,
	0x10, 0xc7, 0x31, 0x31, 0x92, 0x8c, 0x9a, 0xc0, 0x1e, 0x1e, 0x22, 0x0f, 0x5e, 0x62, 0x2e, 0x79,
	0x2d, 0x6c, 0x20, 0x3d, 0xf4, 0xd8, 0x43, 0xdb, 0x5b, 0x0b, 0xc5, 0xa6, 0xe7, 0x60, 0x74, 0x2a,
	0x82, 0xee, 0xda, 0xec, 0x6e, 0x08, 0xfd, 0x76, 0xfd, 0x66, 0x65, 0x57, 0x2d, 0xa6, 0x87, 0xf6,
	0x36, 0x33, 0xfc, 0x76, 0xfc, 0xfb, 0x1b, 0x98, 0xd5, 0x07, 0x2e, 0xf9, 0xba, 0x52, 0x27, 0x6a,
	0xaa, 0xf0, 0x5f, 0xce, 0x79, 0x5e, 0xe2, 0xda, 0x74, 0x7b, 0xf5, 0xba, 0x96, 0x45, 0x85, 0x42,
	0x26, 0x55, 0xdd, 0x00, 0xd1, 0x25, 0xb8, 0xcf, 0xc8, 0xb2, 0x18, 0xdf, 0x14, 0x0a, 0x49, 0xfe,
	0xc2, 0x28, 0x4b, 0xa4, 0xaa, 0x02, 0x6b, 0x6e, 0xad, 0xdc, 0x8d, 0x43, 0xef, 0x74, 0x17, 0x37,
	0xc3, 0xe8, 0x02, 0xbc, 0x06, 0x16, 0x35, 0x67, 0x02, 0x49, 0x08, 0xe3, 0x03, 0xa6, 0x58, 0x1c,
	0x31, 0x33, 0x0f, 0xc6, 0xf1, 0x57, 0x1f, 0xbd, 0x80, 0xff, 0x50, 0x08, 0x89, 0xac, 0x5b, 0xbd,
	0x00, 0xaf, 0x60, 0x69, 0xa9, 0x32, 0xdc, 0xc9, 0x24, 0x17, 0x81, 0x35, 0x1f, 0xae, 0x26, 0xb1,
	0xdb, 0xce, 0xb6, 0x49, 0x2e, 0x34, 0x82, 0xa7, 0x1e, 0x32, 0x68, 0x90, 0x76, 0xa6, 0x91, 0x88,
	0xc2, 0xb4, 0x5b, 0xdb, 0x86, 0xf8, 0x39, 0xf2, 0x02, 0xdc, 0xa7, 0x82, 0xe5, 0x5d, 0x08, 0x02,
	0x76, 0x5d, 0xb0, 0xbc, 0x4d, 0x6b, 0xea, 0x28, 0x02, 0xaf, 0x41, 0xda, 0x85, 0x9a, 0xe1, 0x3d,
	0x86, 0xb3, 0x3c, 0xfa, 0xb0, 0x60, 0x64, 0xf6, 0x92, 0x6b, 0x98, 0x28, 0x29, 0x76, 0x78, 0x44,
	0x26, 0xdb, 0x4f, 0x86, 0xb4, 0xb1, 0x4c, 0x3b, 0xcb, 0x74, 0xdb, 0x59, 0x8e, 0xc7, 0x4a, 0x8a,
	0x7b, 0xcd, 0x92, 0x1b, 0xf0, 0xf5, 0xc3, 0x94, 0x97, 0x25, 0xa6, 0x12, 0xb3, 0x60, 0xf0, 0xeb,
	0x63, 0x4f, 0x49, 0x71, 0xdb, 0xf1, 0xe4, 0x0f, 0x38, 0x82, 0xab, 0x43, 0x8a, 0xc1, 0x70, 0x6e,
	0xad, 0x26, 0x71, 0xdb, 0xe9, 0xbc, 0x59, 0x22, 0x93, 0xc0, 0x36, 0x53, 0x53, 0xeb, 0x99, 0x31,
	0x38, 0x32, 0x06, 0x4d, 0xbd, 0x79, 0x87, 0xe1, 0xa3, 0x3a, 0x91, 0x25, 0xd8, 0xfa, 0x88, 0xc4,
	0xa3, 0xbd, 0xc3, 0x87, 0x3e, 0x3d, 0xbb, 0xec, 0x7f, 0x70, 0x1a, 0xcd, 0x64, 0x4a, 0xcf, 0xce,
	0x18, 0xce, 0xe8, 0x37, 0xff, 0x4b, 0xb0, 0xb5, 0x3e, 0xe2, 0xd1, 0x9e, 0xe8, 0xd0, 0xa7, 0x7d,
	0xa7, 0x7b, 0xc7, 0xfc, 0xdd, 0xd5, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff, 0xbf, 0xfc, 0xfb, 0x1c,
	0xa1, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MuxClient is the client API for Mux service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MuxClient interface {
	// Send data, one item per message, collected from the hum
	Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendResponse, error)
	// Listen to the hum
	Listen(ctx context.Context, in *ListenRequest, opts ...grpc.CallOption) (*ListenResponse, error)
	// Ping debugging endpoint
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
}

type muxClient struct {
	cc *grpc.ClientConn
}

func NewMuxClient(cc *grpc.ClientConn) MuxClient {
	return &muxClient{cc}
}

func (c *muxClient) Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendResponse, error) {
	out := new(SendResponse)
	err := c.cc.Invoke(ctx, "/Mux/Send", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *muxClient) Listen(ctx context.Context, in *ListenRequest, opts ...grpc.CallOption) (*ListenResponse, error) {
	out := new(ListenResponse)
	err := c.cc.Invoke(ctx, "/Mux/Listen", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *muxClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, "/Mux/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MuxServer is the server API for Mux service.
type MuxServer interface {
	// Send data, one item per message, collected from the hum
	Send(context.Context, *SendRequest) (*SendResponse, error)
	// Listen to the hum
	Listen(context.Context, *ListenRequest) (*ListenResponse, error)
	// Ping debugging endpoint
	Ping(context.Context, *PingRequest) (*PingResponse, error)
}

// UnimplementedMuxServer can be embedded to have forward compatible implementations.
type UnimplementedMuxServer struct {
}

func (*UnimplementedMuxServer) Send(ctx context.Context, req *SendRequest) (*SendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Send not implemented")
}
func (*UnimplementedMuxServer) Listen(ctx context.Context, req *ListenRequest) (*ListenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Listen not implemented")
}
func (*UnimplementedMuxServer) Ping(ctx context.Context, req *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}

func RegisterMuxServer(s *grpc.Server, srv MuxServer) {
	s.RegisterService(&_Mux_serviceDesc, srv)
}

func _Mux_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MuxServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Mux/Send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MuxServer).Send(ctx, req.(*SendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mux_Listen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MuxServer).Listen(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Mux/Listen",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MuxServer).Listen(ctx, req.(*ListenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mux_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MuxServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Mux/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MuxServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Mux_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Mux",
	HandlerType: (*MuxServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _Mux_Send_Handler,
		},
		{
			MethodName: "Listen",
			Handler:    _Mux_Listen_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _Mux_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/mux.proto",
}
